### ISSUE TITLE
please add "copy path" to command palette

### ISSUE THREAD

**Issue by DFVSQY** [cg-cnu/vscode-path-tools#1]
same to the title

**Comment by cg-cnu** [comment]
Just to clarify, you meant... copy the path if the cursor is somewhere in the path even with out selection ?

**Comment by DFVSQY** [comment]
![image](https://user-images.githubusercontent.com/8075421/38764873-c059b720-3fe9-11e8-9b00-41f8a2a9e7a7.png)
I hope add "copy path" command, so i can copy the active file path.

**Comment by cg-cnu** [comment]
Gotcha! Will do that 👍 Thanks for the suggestion!

**Comment by cg-cnu** [comment]
Hey @DFVSQY I released a new version of extension with the copy function. 
Other functions include converting ~ to home directory and home directory back to ~.
Test it out and let me know if you got any feedback! 😃

**Comment by DFVSQY** [comment]
@cg-cnu I have a try, it works very well, thank you very much

**Comment by cg-cnu** [comment]
You are welcome! Am closing this issue 👍
